<div class="apagar" id="msg">
    <div class="alert alert-warning " role="alert">
        Campos Vazios
    </div> 
</div>

<section>
    <div class="row">
        <div class="col-md-6">
          <div class="box">
                <div class="box-title">
                    <h5 class="">Login</h5>
                <P>Seja bem-vindo  ao Sistema Auto Lub-Vendas</P>
                                        
                </div>
                <div class="box-body">
                    <div class="box-form">
                        <form id="form_login_fun">
                        <div class="mb-3">
                            <label for="exampleInputEmail1" class="form-label">Login</label>
                            <input type="text" class="form-control" id="login"name="login" aria-describedby="emailHelp">
                           
                        </div>
                        <div class="mb-3">
                            <label for="exampleInputEmail1" class="form-label">Senha</label>
                            <input type="password" class="form-control" id="senha"name="senha" >
                            <!-- <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                        </div>
                        <div class="d-flex justify-content-center">
                            <button type="button" class=" btn-default" id="btn_login_fun">
                                    Logar
                            </button>
                        </div>
                        </form>
                    </div>
                </div>
          </div>
        </div>
        <div class="col-md-6">
           <div class="img-fundo-adm"> 

           </div>
        </div>
    </div>
</section>