<div class="painel-vendas-tabela">
  <div class="config-tabela">
<label for="">Tabela de Prudutos Listados</label>
   <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Produto/Servico</th>
      <th scope="col">Preço</th>
      <th scope="col">Qtd</th>
      <th scope="col">Remover</th>
    </tr>
  </thead>
  <tbody>
    <?php 
    $i=1;
    foreach( $this->view->dados as $value ){
      
      ?>
    <tr>
      <th scope="row"><?= $i++ ?></th>
      <td><?= $value['produto']?></td>
      <td><?= $value['preco']?></td>
      <td><?= $value['qtd']?></td>
      <td>
        <button class="btn btn-danger" onclick='removerItem(<?= $value["id_listagem_venda"]?>)'>
            Remover
        </button>
      </td>
    </tr>
    <?php }  ?>
    
  </tbody>
</table>
  </div>
   
                        </div> 
                        <div class="mt-3 config-precos">
                            <button class="btn btn-success" type="button" 
                            onclick='adicionarPagamento(<?= $this->view->soma ?>,<?= json_encode($this->view->cliente)?>)'>
                                Adicionar Pagamento
                            </button>
                           
                            <div>
                              Soma R$ <span id="valor_total"><?= $this->view->soma ?></span>
                            </div>
                        </div>  
                        </div>