<div class="box-cadastro">
                            <div class="box-cadastro-title">
                                        <h5>Cadastro de Veíuculo</h5>
                            </div>
                            <p></p>
                            <div class="box-cadastro-body">
                                <div>
                                    <form id="form_cadastro_veiculo">
                                        <div class="row">
                                            <div class="col-auto">
                                                <div>
                                                    <label for="" class="form-label">Tipo</label>
                                                    <select name="tipo" id="tipo" class="form-control">
                                                        <option value="">Moto</option>
                                                        <option value="">Carro</option>
                                                        <option value="">Caminhão</option>
                                                    </select>
                                                </div>
                                               
                                            </div>
                                            <div class="col-auto">
                                                <div>
                                                    <label for="" class="form-label">Nome</label>
                                                    <input type="text" name="nome" id="Nome"  class="form-control" placeholder="Ford Ka prata">
                                                </div>
                                               
                                            </div>
                                            <div class="col-auto">
                                                <div>
                                                    <label for="" class="form-label">Placa</label>
                                                    <input type="text" name="placa" id="placa"  class="form-control" placeholder="Fulano de Oliveira">
                                                </div>
                                               
                                            </div>
                                            <div class="mt-3">
                                                <button class="btn btn-success" type="button">
                                                    Salvar
                                                </button>
                                                <button class="btn btn-secondary" type="button">
                                                    Avançar
                                                </button>
                                            </div>
                                          
                                        </div>
                                    </form>
                                </div> 
                            </div>
                       </div>