<div class="box-cadastro">
                            <div class="box-cadastro-title">
                                        <h5>Cadastro de Informações básicas</h5>
                            </div>
                            <div class="box-cadastro-body">
                                <div>
                                    <form id="form_cadastro_cliente_basico">
                                        <div class="row">
                                            <div class="col-6">
                                                <div>
                                                    <label for="" class="form-label">Nome</label>
                                                    <input type="text" name="nome" id="nome"  class="form-control" placeholder="Fulano de Oliveira">
                                                </div>
                                                <div>
                                                    <label for="" class="form-label">Email</label>
                                                    <input type="text" name="email" id="email"  class="form-control" placeholder="email@exemplo.com">
                                                </div>
                                            </div>
                                            <div class="col-6">
                                                <div>
                                                    <label for="" class="form-label">Cpf/Cnpj</label>
                                                    <input type="text" name="cpf_cnpj" id="cpf_cnpj"  class="form-control" placeholder="000.000.000-0">
                                                </div>
                                                <div>
                                                    <label for="" class="form-label">telefone</label>
                                                    <input type="text" name="telefone" id="telefone"  class="form-control" placeholder="">
                                                </div>
                                            </div>
                                            <div class="mt-3">
                                                <button class="btn btn-success" type="button">
                                                    Salvar
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div> 
                            </div>
                       </div>