<div class="box-cadastro">
                            <div class="box-cadastro-title">
                                        <h5>Acesso ao App</h5>
                            </div>
                          
                            <div class="box-cadastro-body">
                                <div>
                                    <form id="form_cadastro_veiculo">
                                        <div class="row">
                                            <div class="col-auto">
                                                <div>
                                                    <label for="" class="form-label">Login</label>
                                                    <input type="text" name="login" id="login" placeholder="Login" class="form-control">
                                                </div>
                                               
                                            </div>
                                            <div class="col-auto">
                                                <div>
                                                    <label for="" class="form-label">Senha</label>
                                                    <input type="password" name="senha" id="senha" placeholder="senha" class="form-control">
                                                </div>
                                               
                                            </div>
                                            <div class="col-auto">
                                                <div>
                                                    <label for="" class="form-label">Confirmar Senha</label>
                                                    <input type="password" name="" id="senha2" placeholder="Confirmar Senha" class="form-control">
                                                </div>
                                               
                                            </div>
                                            <div class="mt-3">
                                                <button class="btn btn-success" type="button">
                                                    Salvar
                                                </button>
                                                
                                            </div>
                                          
                                        </div>
                                    </form>
                                </div> 
                            </div>
                       </div>