<div class="box-cadastro">
                            <div class="box-cadastro-title">
                                        <h5>Visualização </h5>
                            </div>
                          
                            <div class="box-cadastro-body">
                                <div>
                                    <div id="visualziacao_cadastro" class="">
                                        <div class="row">
                                           <div class="col-md-auto "> 
                                            <div class="div-dados-basico">
                                                    <h5>Dados básico</h5>
                                                    <p class="text-secondary">**Poderá ser editado</p>
                                                    <div>
                                                   <p>Nome</p>
                                                   <p class="result">Igorthiago</p>
                                                   <p>Email</p>
                                                   <p class="result">emial@exemplo.com</p>
                                                   <p>CPF/CNPJ</p>
                                                   <p class="result">CNPJ</p>
                                                   <p>Telefone</p>
                                                   <p class="result">92993956161</p>

                                                    </div>
                                            </div>
                                           </div>
                                           <div class="col-md-auto"> 
                                           <div class="div-dados-basico">
                                                    <h5>Veículo</h5>
                                                    <p class="text-secondary">**Poderá ser editado</p>
                                                    <div>
                                                   <p>Tipo</p>
                                                   <p class="result">Moto</p>
                                                   <p>Modelo</p>
                                                   <p class="result">YAMAHA 150, preta</p>
                                                   <p>Placa</p>
                                                   <p class="result">PHPP-4545</p>
                                                  

                                                    </div>
                                            </div>
                                           </div>
                                           <div class="col-md-auto"> 
                                           <div class="div-dados-basico">
                                                    <h5>Login</h5>
                                                    <p class="text-secondary">**Poderá ser editado</p>
                                                    <div>
                                                   <p>Login</p>
                                                   <p class="result">funalo_1</p>
                                                   <p>Senha</p>
                                                   <p class="result"><span class="text-danger">
                                                    Visualizar somente pela ediçaõ
                                                   </span></p>
                                                    </div>
                                            </div>
                                           </div>
                                        </div>
                                    </div>
                                </div> 
                                <div class="finalizar">
                                    <button class="btn btn-primary">
                                        Finalizar
                                    </button>
                                </div>  
                            </div>
                       </div>