<section>
    <div class="row">
        <div class="col-md-12">
            <div class="painel-agendamento"> 
                <div class="painel-agendamento-title">
                        <h5 class="display-5">Agendamento para Atendimento</h5>
                </div>
                <div class="painel-agendamento-body">
                    <div class="">
                        <form action="">
                            <div class="row">
                                 <div class="col-auto">
                                    <label for="">Nome</label>
                                    <input type="text" class="form-control" placeholder="Fulano de Tal">
                                 </div>
                                 <div class="col-auto">
                                    <label for="">Veículo</label>
                                    <select name="veiculo" id="veiculo" class="form-select">
                                        <option value="">Escolha seu veículo</option>
                                    </select>
                                 </div>
                                 <div class="col-auto">
                                    <label for="">Data</label>
                                    
                                    <input type="date" class="form-control" >
                                
                                 </div>
                                 <div class="col-auto">
                                    <label for="">Data</label>
                                    
                                    <textarea name="obs" id="obs" class="form-control" placeholder="OBS."></textarea>
                                
                                 </div>
                                 <div class="mt-3">
                                    <button class="btn btn-success" type="button">
                                        Enviar
                                    </button>
                                 </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>