<section>
    <div class="row">
        <div class="col-md-12">
            <div class="painel-cliente">
                  <div class="painel-cliente-title">
                        <h5 class="display-5">Olá, <?= $_SESSION['nome_cliente']?></h5>
                  </div>
                 
                  <div class="painel-cliente-body">
                        <!-- 
                        <div class="card-painel card-agendamento ">
                              <div class="config-icones "> 
                                    <div class="fundo-icone">
                                          <img src="/img/agendamento.png" alt="">
                                    </div>
                                    <div class="">
                                          <h5>Agendamento de Serviço</h5>
                                    </div>
                              </div>
                              <div class="box-bottom">
                                    <div class="config-descricao">
                                          <div class="config-texto">
                                                <p>Agendamento de horários </p>
                                          </div>
                                          <div class="config-link">
                                               <a onclick="abrirJanela('agendamento','Agendamento','/app/client/home')" class="disabled">
                                               <img src="/img/seta_link.png" alt="">
                                               </a>
                                          </div>
                                    </div>
                              </div>
                        </div> -->
                        <div class="card-painel card-agendamento">
                              <div class="config-icones"> 
                                    <div class="fundo-icone">
                                          <img src="/ibautolub/public/img/historico_compras.png" alt="">
                                    </div>
                                    <div class="">
                                          <h5>Histórico de Compras</h5>
                                    </div>
                              </div>
                              <div class="box-bottom">
                                    <div class="config-descricao">
                                          <div class="config-texto">
                                                <p>Listagem de compras realizadas e notas </p>
                                          </div>
                                          <div class="config-link">
                                               <a onclick="abrirJanela('history','Compras Realizadas','/app/client/home')">
                                               <img src="/ibautolub/public/img/seta_link.png" alt="">
                                               </a>
                                          </div>
                                    </div>
                              </div>
                        </div>
                        <div class="card-painel card-agendamento">
                              <div class="config-icones"> 
                                    <div class="fundo-icone">
                                          <img src="/ibautolub/public/img/produtos_loja.png" alt="">
                                    </div>
                                    <div class="">
                                          <h5>Produtos</h5>
                                    </div>
                              </div>
                              <div class="box-bottom">
                                    <div class="config-descricao">
                                          <div class="config-texto">
                                                <p>Produtos disponíveis para venda</p>
                                          </div>
                                          <div class="config-link">
                                          <a  onclick="abrirJanela('list_product','Listagem de Produtos','/app/client/home')">
                                               <img src="/ibautolub/public/img/seta_link.png" alt="">
                                               </a>
                                          </div>
                                    </div>
                              </div>
                        </div>
                        <div class="card-painel card-agendamento">
                              <div class="config-icones"> 
                                    <div class="fundo-icone">
                                          <img src="/ibautolub/public/img/add_car.png" alt="">
                                    </div>
                                    <div class="">
                                          <h5>Veículo</h5>
                                    </div>
                              </div>
                              <div class="box-bottom">
                                    <div class="config-descricao">
                                          <div class="config-texto">
                                                <p>Adicione  veículos para gerenciamento da troca de óleo</p>
                                          </div>
                                          <div class="config-link">
                                                <a onclick="abrirJanela('add_car','Gerenciamento','/app/client/home')">
                                               <img src="/ibautolub/public/img/seta_link.png" alt="">
                                               </a>
                                          </div>
                                    </div>
                              </div>
                        </div>
                        
           
                  </div>
                  
            </div>  
        </div>
    </div>
</section>