<section class="">
    <div class="row">
        <div class="col-md-12">
            <div class="painel-produtos">
                <div class="painel-produtos-title">
                            <h5 class="display-5">Listagem de produtos</h5>
                            <p>lista de produtos disponíveis</p>
                            <hr>
                </div>
                <div id="result_product">
                    
                    
                </div>
            
            </div>
        </div>
    </div>
</section>