<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>iB Auto Lub</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="/ibautolub/public/css/cssCliente.css">

</head>
<body>
<nav class="navbar fixed-top">
  <div class="container-fluid">
  <img src="/ibautolub/public/img/logo1.png" alt="" width="160">
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
     <img src="/ibautolub/public/img/menuFritas.png" width="50">
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Olá, <?= $_SESSION['nome_cliente']?></h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/app/client/home">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" 
            href="/app/client/manager_profile?n=R2VyZW5jaWFyIFBlcmZpbA==&b=L2FwcC9jbGllbnQvaG9tZQ==">Gerenciamento Perfil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/app/client/sair">Sair</a>
          </li>
        </ul>
       
      </div>
    </div>
  </div>
</nav>
    <?php 
    $this->content();
    ?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="/ibautolub/public/js/cliente.js"></script>
</body>
</html>