<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>iB Auto Lub</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="/ibautolub/public/css/cssAdm.css">

</head>
<body>
<nav class="navbar fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
    <img src="/ibautolub/public/img/logo1.png" alt="" width="160">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
     <img src="/ibautolub/public/img/menuFritas.png" width="50">
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Olá, <?= $_SESSION['nome']?></h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/app/adm/home">Home</a>
          </li>
          <?php if($_SESSION['permissao'] == 'S') {?>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" 
            href="/app/adm/cadastro_usuario?n=Q2FkYXN0cmFyIFVzdeFyaW9z&b=L2FwcC9hZG0vaG9tZQ==">
            Cadastrar Funcionario
          </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" 
            href="/app/adm/manager_product?n=R2VyZW5jaW1lbnRv&b=L2FwcC9hZG0vaG9tZQ==">
            Cadastrar Produtos
          </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" 
            href="/app/adm/manager_view?n=R2VyZW5jaWFtZW50byBHZXJlYWw=&b=L2FwcC9hZG0vaG9tZQ==">
              Gerenciamento
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" 
            href="/app/adm/contas_apagar?n=Q29udGFzIGEgUGFnYXIK=&b=L2FwcC9hZG0vaG9tZQ==">
            Contas a pagar
            </a>
          </li>
          <?php } ?>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" 
            href="/app/adm/report?n=UmVwb3J0&b=L2FwcC9hZG0vaG9tZQ==">
              Relatórios
            </a>
          </li>
          <?php if($_SESSION['permissao'] == 'S') {?>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" 
            href="/app/adm/form_add_funcao?n=Tm92bw==&b=L2FwcC9hZG0vaG9tZQ==">
            Adicionar Função
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" 
            href="/app/adm/form_add_adm?n=Tm92byBBZG0=&b=L2FwcC9hZG0vaG9tZQ==">
            Adicionar Administrador
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" 
            href="/app/adm/add_qtd_product?n=QWRpY2lvbmFyIFF0ZA===&b=L2FwcC9hZG0vaG9tZQ==">
            Adicionar Qtd Produtos
            </a>
          </li>
          <?php } ?>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" 
            href="/app/adm/history?n=QWRpY2lvbmFyIFF0ZA===&b=L2FwcC9hZG0vaG9tZQ==">
            Histórico
            </a>
          </li>
          <?php if($_SESSION['permissao'] == 'S') {?>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" 
            href="/app/adm/edit_profile?id_user=<?=$_SESSION['id']?>&n=RWRpdGFyIFBlcmZpbA===&b=L2FwcC9hZG0vaG9tZQ==">
              Editar Perfil
            </a>
          </li>
          <?php } ?>
          
          
          <li class="nav-item">
            <a class="nav-link" aria-current="page" 
            href="/app/adm/finalizar_sessao">
              Sair
            </a>
          </li>
        </ul>
       
      </div>
    </div>
  </div>
</nav>
    <?php 
    $this->content();
    ?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="/ibautolub/public/js/adm.js"></script>
</body>
</html>