<section>
    <div class="row">
        <div class="col-md-12">
            <div class="painel-sucesso">
                <div class="card-sucesso">
                    <div class="card-sucesso-title">
                        <h5 class="text-danger">
                        <img src="/img/error.png" class="mr-2" alt="">
                        <?= $this->view->title ?>
                        </h5>
                    </div>
                    <div class="card-sucesso-body">
                        <div>
                            <p>
                                <?= $this->view->msg ?>
                            </p>
                            <div class="center">
                            <a href=" <?= $this->view->link ?>" class="btn btn-danger">
                                Voltar
                            </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>