<section class="">
    <div class="row">
        <div class="col-md-12">
            <div class="painel-pesquisar-container">
                <div class="painel-pesquisar">
                
                        <div class="painel-pesquisar-title">
                            <h5 class="display-5">Pesquisar Vendas</h5>
                        </div>
                        <span class="text-danger">* Obrigatório</span>
                        <div class="painel-pesquisa-body">
                            <div class="config-card">
                                <label for="">Código de Venda <span class="text-danger">*</span></label>
                                <input type="text" name="codigo_venda" id="codigo_venda"
                                class="form-control" placeholder="Codigo de compra gerado">
                                <div id="validationServerUsernameFeedback" 
                                class="invalid-feedback">
                                    Preencha o campo
                                </div>
                            </div>
                            
                            <div>
                                <button class="btn btn-secondary" onclick="pesquisarItem()">Pesquisar</button>
                            </div>
                        </div>
                </div>
            </div>
            <div id="conteudo_pesquisa">
            
            </div>
            
        </div>
    </div>
</section>