
<div class="apagar" id="msg">
    <div class="alert alert-danger" role="alert">
        Campos Vazios
    </div> 
</div>
<section class="mt-5" >
    <div class="row">
        <div class="col-md-12">
          <div class="box-cadastrar-cliente">
                <div class="box-cadastrar-cliente-title">
                    <h5 class="display-5">Cadastro de Clientes</h5>
                </div>
                <div class="box-cadastrar-cliente-body" >
                    <div class="">
                    <form id="form_cadastro_cliente_basico" class="alinhar">
                                        <div class="row">
                                        
                                            <div class="col-auto  mt-4">
                                            <h5>Dados Básicos</h5>
                                                <div >
                                                    <label for="" class="form-label">Nome</label>
                                                    <input type="text" name="nome" id="nome"  class="form-control" placeholder="Fulano de Oliveira">
                                                    <div class="invalid-feedback">
                                                       Nome inválido
                                                    </div>
                                                </div>
                                                <div class="mt-4 ">
                                                    <label for="" class="form-label">Email</label>
                                                    <input type="text" name="email" id="email"  class="form-control" placeholder="email@exemplo.com">
                                                    <div class="invalid-feedback">
                                                        Email inválido
                                                    </div>
                                                </div>
                                                <div class="mt-4">
                                                    <label for="" class="form-label">Cpf/Cnpj</label>
                                                    <input type="text" name="cpf_cnpj" id="cpf_cnpj"  class="form-control" placeholder="000.000.000-0">
                                                    <div class="invalid-feedback">
                                                   Cpf inválido
                                                    </div>
                                                </div>
                                                <div class="mt-4">
                                                    <label for="" class="form-label">telefone</label>
                                                    <input type="text" name="telefone" id="telefone"  
                                                    class="form-control" placeholder="00 00000000">
                                                    <div id="telefone" class="invalid-feedback">
                                                  telefone inválido
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-auto  mt-4">
                                                <h5>Login</h5>
                                                <div>
                                                    <label for="" class="form-label">Login</label>
                                                    <input type="text" name="login" id="login" placeholder="Login" class="form-control"
                                                    onchange="verificarNomeLogin('login','salvar_dados_basico')"
                                                    >
                                                    <div id="validationServer04Feedback" class="invalid-feedback">
                                                   Usuário disponível
                                                    </div>
                                                </div>
                                                <div class="mt-4"> 
                                                    <label for="" class="form-label">Senha</label>
                                                    <input type="password" name="senha" id="senha" placeholder="senha" class="form-control">
                                                    <div id="validationServer04Feedback" class="invalid-feedback">
                                                    Senha inválida
                                                    </div>
                                                </div>
                                                <div class="mt-4">
                                                    <label for="" class="form-label">Confirmar Senha</label>
                                                    <input type="password" name="" id="senha2" placeholder="Confirmar Senha" class="form-control">
                                                    <div id="validationServer04Feedback" class="invalid-feedback">
                                                    Senha inválida
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            <div class="mt-3">
                                                <button class="btn btn-success" type="button" id="salvar_dados_basico" onclick="salvarDados()">
                                                    Salvar
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                    </div>
                </div>
          </div>
        </div>
    </div>
</section>