
<div class="apagar" id="msg">
    <div class="alert alert-danger" role="alert">
       Campo vazio
    </div> 
</div>
<section class="mt-5" >
    <div class="row">
        <div class="col-md-12">
          <div class="box-cadastrar-cliente">
                <div class="box-cadastrar-cliente-title">
                    <h5 class="display-5">Cadastro de Clientes</h5>
                </div>
                <div class="box-cadastrar-cliente-body" >
                    <div class="">
                    <form id="form_editar_login_cliente" class="alinhar">
                                        <div class="row">
                                    
                                            <div class="col-auto  mt-4">
                                                
                                                <div>
                                                    <label for="" class="form-label">Login</label>
                                                    <input type="text" name="login" id="login_atualizar" placeholder="Login" class="form-control"
                                                    onchange='verificarSenhaCliente(<?= json_encode($this->view->dados["login"])?>)'
                                                    value="<?= base64_decode($this->view->dados['login'])?>"
                                                    >
                                                    <div id="validationServer04Feedback" class="invalid-feedback">
                                                   Usuário indisponível
                                                    </div>
                                                </div>
                                            </div>
                                                <div class="col-auto">
                                                <div class="mt-4"> 
                                                    <label for="" class="form-label">Senha</label>
                                                    <input type="password" name="senha" id="senha_atualizar" placeholder="senha" class="form-control">
                                                    <div id="validationServer04Feedback" class="invalid-feedback">
                                                    Senha inválida
                                                    </div>
                                                </div>
                                                </div>
                                                <div class="col-auto">
                                                <div class="mt-4">
                                                    <label for="" class="form-label">Confirmar Senha</label>
                                                    <input type="password" name="" id="senha2" placeholder="Confirmar Senha" class="form-control">
                                                    <div id="validationServer04Feedback" class="invalid-feedback">
                                                    Senha inválida
                                                    </div>
                                                </div>
                                                </div>
                                               
                                                <div class="mt-3 d-flex aling-itens-center">
                                                <button class="btn btn-success" type="button" id="btn_editar_senha" onclick='editarSenhaCliente(<?= $_GET["id"]?>)'>
                                                    Salvar
                                                </button>
                                               

                                                </div>
                                                
                                            </div>
                                            
                                        </div>
                                        
                                    </form>
                    </div>
                </div>
          </div>
        </div>
    </div>
</section>