<section class="mt-5">
    <div class="row">
        <div class="col-md-12">
           <div class="box">
                <div class="box-title">
                    <h5 class="display-5">Acésso Rápido</h5>
                </div>
                <div class="box-body">
                    <div class="box-opcoes">
                        <div class="card-opcao">
                            <div class="card-opcao-title">
                                <!-- Senm rtitulo -->
                            </div>
                            <div class="card-opcao-body" 
                            onclick='abrirJanela("cadastrar_cliente","Cadastrar Cliente","/app/fun/home")'>
                                <div class="config-img">
                                    <img src="/ibautolub/public/img/user.png" width="150">
                                    <h3 class="display-5 text-white">Cadastro de Clientes</h3>
                                </div>
                            </div>
                        </div>
                        <div class="card-opcao"
                        onclick='abrirJanela("venda","Registrar Vendas","/app/fun/home")'
                        >
                            <div class="card-opcao-title">
                                <!-- Senm rtitulo -->
                            </div>
                            <div class="card-opcao-body" >
                                <div class="config-img">
                                    <img src="/ibautolub/public/img/venda.png" width="150">
                                    <h3 class="display-5 text-white">Registrar Vendas</h3>
                                </div>
                            </div>
                        </div>
                        
                        <div class="card-opcao"
                        onclick='abrirJanela("pesquisar_venda","Buscar Vendas","/app/fun/home")'
                        >
                            <div class="card-opcao-title">
                                <!-- Senm rtitulo -->
                            </div>
                            <div class="card-opcao-body">
                                <div class="config-img">
                                    <img src="/ibautolub/public/img/pesquisar_compra.png" width="150">
                                    <h3 class="display-5 text-white">Pesquisar Venda</h3>
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>
                </div>
           </div>
        </div>
    </div>
</section>