<div class="apagar" id="msg">
    <div class="alert alert-danger" role="alert">
        É necessário ter algum valor para finalizar a Venda
    </div> 
</div>
<div class="apagar" id="finalizar_compra">
<div class="painel_entrada_valor">
        
        <div class="painel_entrada_valor-title">
            <h5 class="display-5">Finalizar Venda</h5>
            <button class="btn btn-danger" id="btn_fechar_venda" type="button"
            onclick="fecharBlocoVenda()">
                X
            </button>
        </div>
        <div class="painel_entrada_valor-body">
            <div class="config-layout-dados"> 
                <div>
                    <p><b>Dados da Compra</b></p>
                    <p>Valor da compra: </p>
                    <p id="valor_compra_final"></p>
                    <p id="cliente_final"></p>
                </div>
                <div class="mr">
                        <p><b>Tipo de compra</b></p>
                        <div>
                                                <div class="form-check">
                        <input class="form-check-input" type="radio" name="flexRadioDefault" id="compra"  checked onchange="selecaoCompra()">
                        <label class="form-check-label" for="compra" >
                            Compras
                        </label>
                        </div>
                        <div class="form-check">
                        <input class="form-check-input" type="radio" name="flexRadioDefault" id="orcamento"   onchange="selecaoOrcamento()">
                        <label class="form-check-label" for="orcamento">
                           Orçamento
                        </label>
                        </div>
                        </div>
                        <div class="invalid-feedback">
                                Escolha um item
                        </div>
                    </div>
                <div>
                   
                    <div id="valor_pagamento">
                        <p><b>Tipo Pagamento</b></p>
                        <select name="" id="selecao_pagamento" class="form-control">
                            <option value="">Escolha um tipo</option>
                            <?php foreach($this->view->dados_pagamento as $value){?>
                            <option value="<?= $value['id_tipo']?>"><?= $value['nome']?></option>
                            <?php } ?>
                        </select>
                        <div class="invalid-feedback">
                                Escolha um item
                        </div>
                    </div>
                </div>
                <div id="form_envio">
                    <p><b>Valor de Entrada</b></p>
                    <form id="form_enivar_pagamento">
                        <div class="ml-1">
                            <input type="number"  step="0.01" name="valor_entrada" id="valor_entrada" class="form-control"
                            placeholder="R$ 00,00"
                            >
                            <div class="invalid-feedback">
                            Digite valor
                            </div>
                        </div>
                        <div class="config-layout-dados">
                        <button class="btn btn-success" 
                type="button" id="btn_enviar_pagamento" onclick="finalizarVenda()">
                    Finalizar Venda
                </button>
            </div>
                    </form>
                    
                </div>
                
            </div>
            
        
        </div>
</div>
</div>

<div id="result_produto" >

</div>

<section>
   <div class="row">
    <div class="col-md-12">
        <div class="painel-vendas">
            <p class="text-danger"> Antes de Efetuar a Venda, o cliente deve está cadastrado no sistema(obrigatório)</p>
            <p class="text-danger"> Para Adicionar um Veículo acesse o Gerencimaneto de clientes(obrigatório pois será usado no App)</p>
            <p class="text-danger">* (obrigatório)</p>
            <div class="painel-vendas-title">
                <h5 class="display-5 ">Efetuar Vendas</h5>
            </div>
            <div class="painel-vendas-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="painel-vendas-dados">
                                <div class="row">
                                <div class="col-md-auto">
                                    <label for="">Cliente</label>
                                    <select name="" id="cliente_id" class="form-select">
                                        <option value="">Escolha um clinete para inicar a Venda</option>
                                        <?php foreach($this->view->dados_cliente as $value){?>
                                            <option value="<?= $value['id_cliente']?>"><?= $value['nome']?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                                <div class="col-md-auto">
                                    <label for="">Produto</label>
                                    <input type="text" id="nome_produto"
                                    placeholder="Pesquise pelo Serviço ou Produto"
                                    class="form-control"
                                    >
                                </div>
                                <div class="mt-4">
                                    <button class="btn btn-primary" type="button" id="btn_pesquisar"onclick="procurarProduto()">
                                        Pesquisar
                                    </button>
                                </div>
                                </div>
                                
                            
                        </div> 
                        
                    </div>
                    <div class="col-md-6 mt-3">
                       
                        <div id="componente_tabela">
                          
                        
                        
                        </div>
                        
                       
                </div>
            </div>
        </div>
    </div>
   </div>
</section>