<div class="apagar" id="msg_sucesso">
    <div class="alert alert-success" role="alert">
      Alterado com sucesso
    </div> 
</div>
<div class="apagar" id="msg_erro">
    <div class="alert alert-danger" role="alert">
      Erro
    </div> 
</div>
<section class="">
    <div class="row">
        <div class="col-md-12">
           <div class="view-despesas">
                <div class="view-despesas-title">
                    <h5 class="display-5">Selecione um Produto e adicione a quanitdade</h5>
                </div>
                <div class="row">
                <div class="col-auto">
                    <input type="text" placeholder="Pesquisar Item" class="form-control" onkeyup='pesquisarProduto(this.value)'>
                    <div class="invalid-feedback">
                        Campos inválido
                    </div>
                </div>
                </div>
                <hr>
                <div class="" id="conteudo_tabela">
                    
                </div>
           </div>
    </div>
    </div>
</section>