<div class="apagar" id="msg_sucesso">
    <div class="alert alert-success" role="alert">
       Salvo com sucesso
    </div> 
</div>
<div class="apagar" id="msg_erro">
    <div class="alert alert-danger" role="alert">
       Erro ao salvar
    </div> 
</div>
<section>
    <div class="row">
        <div class="col-md-12">
            <div class="box-cadastramaneto">
                    <div class="box-cadastramento-title">
                        <h5 class="display-5">Cadastro de Receita e Despesas</h5>

                    </div>
                    <div class="box-cadastramento-body">
                            <div class="config-filtro">
                                <div>
                                    <p>Escolha uma opção para cadastrar as contas</p>
                                <div>
                                    <div class="d-flex justity-content-between">
                                            <button class="btn btn-success m-2" onclick="abrirReceita()"> 
                                                Receita
                                            </button>
                                            <button class="btn btn-danger m-2" onclick="abrirDespesa()"> 
                                                Despesa
                                            </button>
                                        
                                    </div>
                                </div>
                                </div>
                             
                                <div class="box-filtro">
                                <div class="config-opcoes">
                                    <div class="group-label">
                                          <div class="box-pesquisa">
                                                <label class="label">Configuração de Data</label>
                                                <div class="config-data">
                                                    <div class="m-3">
                                                        <label for="ml-3">Data Inicial</label>
                                                        <input type="date" class="form-control" id="dt_inicial">
                                                    </div>
                                                    <div class="m-3">
                                                        <label for="">Data Final</label>
                                                        <input type="date" class="form-control" id="dt_final">
                                                    </div>
                                                    <div class="m-3">
                                                        <button class="btn btn-secondary" onclick="pesquisarPorData()">
                                                            Pesquisar
                                                        </button>
                                                    </div>
                                                </div>  
                                          </div>
                                          
                                    </div>
                                    <div class="group-label">
                                          <div class="box-pesquisa">
                                                <label class="label">Ativo e Inativo</label>
                                                <div class="config-data">
                                                    <div class="m-3">
                                                        
                                                        <input type="radio" class="" id="ativo" name="" onchange="verificarStatus('ativo')">
                                                        <label for="ml-3" for="ativo">Ativo</label>
                                                    </div>
                                                    <div class="m-3">
                                                        
                                                        <input type="radio" class="" id="inativo" name="" onchange="verificarStatus('inativo')">
                                                        <label for="ml-3" for="inativo">Inativo</label>
                                                    </div>
                                                </div>  
                                          </div>
                                          
                                    </div>
                                    <div class="group-label">
                                          <div class="box-pesquisa">
                                                <label class="label">Informações</label>
                                                <div class="config-data">
                                                    <div class="m-3">
                                                       <p><b>Contas Ativas</b>: <span id="contas_ativa"></span> </p>
                                                       <p><b>Contas Inativas</b>: <span id="contas_inativas"></span></p>
                                                       <p><b>Contas Pagas</b>: <span id="contas_pagas"></span></p>
                                                       <p><b>Contas a Pagar</b>: <span id="contas_a_pagar"></span></p>
                                                       <p><b>Receita</b>: <span id="receita"></span></p>
                                                       <p><b>Total</b>: <span id="soma"></span></p>
                                                    </div>
                                                  
                                                </div>  
                                          </div>
                                          
                                    </div>
                                </div>
                               
                                </div>
                            </div>
                            
                            <hr>
                            
                    </div>
                    <div id="cadastrar_receita" class="d-none">
                        <div class="painel-cadastrar-receita">
                            <div class="form-cadastrar">
                                <div class="form-cadastrar-title">
                                    <h5 class="display-5">Cadatrar  receita</h5>
                                    <div class="btn btn-danger" onclick="fecharReceita()">
                                        X
                                    </div>
                                </div>
                                <div class="form-cadastrar-body">
                                    <div class="row">
                                        <div class="col-auto">
                                            <label for="">Nome Receita</label>
                                            <input type="text" class="form-control" placeholder="Ex: Compras ou Boletos" id="nome">
                                            <div class="invalid-feedback">
                                                Campo vazio
                                            </div>
                                        </div>
                                        <div class="col-auto">
                                            <label for="">Valor</label>
                                            <input type="number" class="form-control" step="0,01"  id="valor">
                                            <div class="invalid-feedback">
                                                Campo vazio
                                            </div>
                                        </div>
                                        
                                        <div class="col-auto">
                                            <label for="">Categoria</label>
                                            <select name="" id="categoria" class="form-control">
                                            <option value="Pagamentos">Pagamentos</option>
                                            <option value="Recebimento">Recebimento</option>
                                            <option value="Pix">Pix</option>
                                           </select>
                                            <div class="invalid-feedback">
                                                Campo vazio
                                            </div>
                                        </div>
                                        <div class="col-auto">
                                            <label for="">Data</label>
                                            <input type="date" class="form-control"  id="data">
                                            <div class="invalid-feedback">
                                                Campo vazio
                                            </div>
                                        </div>
                                        <div class="col-auto">
                                            <label for="">obs</label>
                                          <textarea id="obs" class="form-control"></textarea>
                                           
                                        </div>
                                        <div class="col-auto mt-4">
                                            <button class="btn btn-secondary" onclick="cadastrarReceita()">
                                                Salvar
                                            </button>
                                            
                                           
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="cadastrar_despesa" class="d-none">
                        <div class="painel-cadastrar-receita">
                            <div class="form-cadastrar">
                                <div class="form-cadastrar-title">
                                    <h5 class="display-5">Cadatrar  Despesa</h5>
                                    <div class="btn btn-danger" onclick="fecharDespesa()">
                                        X
                                    </div>
                                </div>
                                <div class="form-cadastrar-body">
                                    <div class="row">
                                        <div class="col-auto">
                                            <label for="">Nome Despesa</label>
                                            <input type="text" class="form-control" placeholder="Ex: Compras ou Boletos" id="nome_despesa">
                                            <div class="invalid-feedback">
                                                Campo vazio
                                            </div>
                                        </div>
                                        <div class="col-auto">
                                            <label for="">Valor</label>
                                            <input type="number" class="form-control" step="0,01"  id="valor_despesa">
                                            <div class="invalid-feedback">
                                                Campo vazio
                                            </div>
                                        </div>
                                        
                                        <div class="col-auto">
                                            <label for="">Categoria</label>
                                            <select name="" id="categoria_despesa" class="form-control">
                                            <option value="agua">Água</option>
                                            <option value="luz">Luz</option>
                                            <option value="internet">Internet</option>
                                           </select>
                                            <div class="invalid-feedback">
                                                Campo vazio
                                            </div>
                                        </div>
                                        <div class="col-auto">
                                            <label for="">Data Vencimento</label>
                                            <input type="date" class="form-control"  id="data_despesa">
                                            <div class="invalid-feedback">
                                                Campo vazio
                                            </div>
                                        </div>
                                        <div class="col-auto">
                                            <label for="">obs</label>
                                          <textarea id="obs_despesa" class="form-control"></textarea>
                                           
                                        </div>
                                        <div class="col-auto mt-4">
                                            <button class="btn btn-secondary" onclick="cadastrarDespesa()">
                                                Salvar
                                            </button>
                                            
                                           
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="result_count">
                            
                    </div>
            </div>
        </div>
    </div>
</section>