<div class="apagar" id="msg">
    <div class="alert alert-danger" role="alert">
        Campos Vazios
    </div> 
</div>
<!-- <div class="apagar" id="senha_verificar">
    <div class="alert alert-secondary" role="alert">
        Senha inválida
    </div> 
</div> -->
<section>
<div class="painel-formulário">
        <form id="form_adm_edit">
            <div class="row">
                <div class="col-md-4">
                    <div class="mb-3">
                    <label for="validationServer03" class="form-label">Nome</label>
                    <input type="text" class="form-control" id="nome_adm" name="nome_adm" aria-describedby="validationServer03Feedback" 
                    value="<?=  $this->view->dados['nome']?>"
                    >
                    <div id="validationServer03Feedback" class="invalid-feedback">
                   Campo Vazio
                    </div>
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email_adm" name="email" placeholder="fulano@gmail.com"
                        value="<?=  $this->view->dados['email']?>"
                        >
                        <div id="validationServer03Feedback" class="invalid-feedback">
                   Email Vazio
                    </div>
                    </div>
                </div>
                <div class="col-md-4">
                    
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Permisão de Cadastro</label>
                        <select name="permissao" id="permissao" class="form-control">
                            <option value="<?=  $this->view->dados['permissao_cadastro']?>">Atual: <?=  $this->view->dados['permissao_cadastro']?></option>
                            <option value="S">Sim</option>
                            <option value="N">Não</option>
                        </select>
                        <div id="validationServer03Feedback" class="invalid-feedback">
                   Sem seleção
                    </div>
                    </div>
                </div>
                
            </div>
            <div class="">
                <button type="button" class="btn btn-success" id="btn_edit_adm" onclick='editarAdm(<?=$this->view->id?>)'>
                    Editar
                </button>
                
            </div>
        </form>
    </div>
    </section>