<div id="painel_form" class="">
    
</div>
<section class="mt-5">
    <div class="row">
        <div class="col-md-12">
           <div class="box">
                <div class="box-title">
                    <h5 class="display-5">Cadastramento de Produtos e Serviços</h5>
                </div>
                <div class="box-body">
                    <div class="box-opcoes">
                        <div class="card-opcao">
                            <div class="card-opcao-title">
                                <!-- Senm rtitulo -->
                            </div>
                            <div class="card-opcao-body" 
                            onclick='abrirJanela("add_product","Cadastrar Produto","/app/adm/manager_product?n=R2VyZW5jaW1lbnRv&b=L2FwcC9hZG0vaG9tZQ==")'
                            >
                                <div class="config-img">
                                    <img src="/ibautolub/public/img/box.png" width="150">
                                    <h3 class="display-5 text-white">Cadastro de Produtos</h3>
                                </div>
                            </div>
                        </div>
                        <div class="card-opcao">
                            <div class="card-opcao-title">
                                <!-- Senm rtitulo -->
                            </div>
                            <div class="card-opcao-body"
                            onclick='abrirJanela("add_service","Cadastrar Servico","/app/adm/manager_product?n=R2VyZW5jaW1lbnRv&b=L2FwcC9hZG0vaG9tZQ==")'
                            >
                                <div class="config-img">
                                    <img src="/ibautolub/public/img/servico.png" width="150">
                                    <h3 class="display-5 text-white">Cadastro de Serviços</h3>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
           </div>
        </div>
    </div>
</section>