<div id="painel_form" class="">
    
</div>
<section class="mt-5">
    <div class="row">
        <div class="col-md-12">
           <div class="box">
                <div class="box-title">
                    <h5 class="display-5">Cadastrar usuários para acessar o sistema</h5>
                </div>
                <div class="box-body">
                    <div class="box-opcoes">
                        <div class="card-opcao">
                            <div class="card-opcao-title">
                                <!-- Senm rtitulo -->
                            </div>
                            <div class="card-opcao-body" 
                            onclick='abrirJanela("form_add_user","Cadastrar","/app/adm/cadastro_usuario?n=R2VyZW5jaW1lbnRv&b=L2FwcC9hZG0vaG9tZQ==")'
                            >
                                <div class="config-img">
                                    <img src="/ibautolub/public/img/addUser.png" width="150">
                                    <h3 class="display-5 text-white">Cadastro funcionários</h3>
                                </div>
                            </div>
                        </div>
                        <div class="card-opcao">
                            <div class="card-opcao-title">
                                <!-- Senm rtitulo -->
                            </div>
                            <div class="card-opcao-body"
                            onclick='abrirJanela("listagem","Listagem","/app/adm/cadastro_usuario?n=R2VyZW5jaW1lbnRv&b=L2FwcC9hZG0vaG9tZQ==")'
                            >
                                <div class="config-img">
                                    <img src="/ibautolub/public/img/mecanico.png" width="150">
                                    <h3 class="display-5 text-white">Editar Usuário</h3>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
           </div>
        </div>
    </div>
</section>