
<section class="">
    <div class="row">
        <div class="col-md-12">
           <div class="view-despesas">
                <div class="view-despesas-title">
                    <h5 class="display-5">Histórico do Sistema</h5>
                </div>
                <div class="row">
                <div class="col-md-6">
                    <label for="">Opção</label>
                    <select name="" id="opcao_tipo" onchange="escolherTipoLog()">
                        <option value="">Esolha uma opção</option>
                        <option value="erro">Erro</option>
                        <option value="sistema">Sistema</option>
                        <option value="vendas">Vendas</option>
                        <option value="troca">Troca</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <ul>
                        <li><b>Erro</b>-> Registro de <span class="bg-danger text-white ">Erros</span> ocorrido em todo o Sistema</li>
                        <li><b>Sistema</b>-> Registro de <span class="bg-warning text-white ">Alterações</span> feito em todo o sitema</li>
                        <li><b>Vendas</b>-> Históirco de  <span class="bg-success text-white ">Vendas</span> feito por funcionários</li>
                        <li><b>Troca</b>-> Históirco de  <span class="bg-secondary text-white ">Trocas</span> feito por funcionários</li>
                    </ul>
                </div>
                </div>
                <hr>
                <div class="" id="tabela_conteudo">
                   
                </div>
           </div>
    </div>
    </div>
</section>