<section class="not_scroll">
    <div class="row">
        <div class="col-md-12">
            <div class="box-manager">
                <div class="box-manager-fixed">
                    <div class="config-menu">
                       <ul>
                            <li id="servico" onclick="getTable('listagem_servico','servico')">Serviços</li>
                            <li id="produto"  onclick="getTable('listagem_produtos','produto')">Produtos</li>
                            <li id="adm" onclick="getTable('listagem_adm','adm')">ADM's</li>
                            <li id="funcionario" onclick="getTable('listagem_funcionario','funcionario')">Funcionários</li>
                            <li id="caixa" onclick="getTable('listagem_caixa','caixa')">Caixa</li>
                       </ul>
                    </div>
                </div>
                <div class="box-manager-body">
                    <div class="box-manager-table" id="manager_table">
                        Escolha uma opção
                       
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</section>